version: '2'
services:
  web:
    build: .
    ports:
      - "80:8000"
    restart: always
    # env_file: ./api/.env -- if need to move the env vars
    environment:
      NODE_ENV: production
      PORT: 8000
