version: "3.7"
services:
  api:
    build:
      context: ./api/
    command: yarn dev
    volumes:
      - ./api/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: "${NODE_ENV}"
      CHOKIDAR_USEPOLLING: "${CHOKIDAR_USEPOLLING}"
  web:
    build:
      context: ./web/
    command: yarn dev
    volumes:
      - ./web/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - api
    ports:
      - "3000:3000"
